// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgM5p6JCq-HqP4hktD-rlRkXxJt07t5CQ',
    appId: '1:664402979999:web:4b41fef697aa56543c06aa',
    messagingSenderId: '664402979999',
    projectId: 'brew-crew578',
    authDomain: 'brew-crew578.firebaseapp.com',
    storageBucket: 'brew-crew578.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcfBiqkPxUlc6ehO4-jaI4WAZcqGc7j8',
    appId: '1:664402979999:android:b4fbd2b70fb8fc643c06aa',
    messagingSenderId: '664402979999',
    projectId: 'brew-crew578',
    storageBucket: 'brew-crew578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx0Hd543Soa424eg_6As4ZD-rsCotckcw',
    appId: '1:664402979999:ios:d8fb656ced2cd2a13c06aa',
    messagingSenderId: '664402979999',
    projectId: 'brew-crew578',
    storageBucket: 'brew-crew578.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );
}
